title: Bharath Krishnamurthy

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# remote_theme: pages-themes/modernist@v0.2.0
# plugins:
# - jekyll-remote-theme

# logo: Images/Pic.png

# gem "github-pages", group: :jekyll_plugins
